version: '2.4'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    networks:
      - skyhawk
    ports:
      - 8001:80
      - 4433:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/configs:/configs:ro
      - ./data/acme.json:/acme.json:rw
      - ./data/logs:/logs:rw
    environment:
      - CF_API_KEY=
      - CF_API_EMAIL=
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-https.entrypoints=https
      - traefik.http.routers.traefik-https.rule=Host(`treafik.domain.com`)
      - traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIKADMIN}
      - traefik.http.routers.traefik-https.middlewares=traefik-auth
      - traefik.http.routers.traefik-https.service=api@internal
      - traefik.http.routers.traefik-https.tls=true
      - traefik.http.routers.traefik-https.tls.certresolver=dns
      - traefik.http.routers.traefik-https.tls.domains[0].main=domain.com
      - traefik.http.routers.traefik-https.tls.domains[0].sans=*.domain.com
      - "traefik.http.middlewares.strip.stripprefix.prefixes=/"
    
    read_only: true

networks:
  skyhawk:
    external: true
